networks:
  default:
    external: true
    name: cvdp-bridge-hackathon-agentic-obfuscated-ebc4cca9
services:
  agent:
    environment:
      OPENAI_USER_KEY: null
    image: cvdp-example-agent
    networks:
    - default
    volumes:
    - ./docs:/code/docs
    - ./rtl:/code/rtl
    - ./verif:/code/verif
    - ./rundir:/code/rundir
    - ./prompt.json:/code/prompt.json
    working_dir: /code
version: '3'
